### PR TITLE
Fix missing logos

### LINKED ISSUE #10: Logos are missing
On this page: https://cookbooks.projectpythia.org/mpl-colorbar-cookbook/notebooks/mpl-colorbar-cookbook.html
the logos seem to be missing!

### PR DESCRIPTION
**Pull request by hCraker**
Closes #10

### CODE REVIEW

**Comment by hCraker** [comment]
I decided to reduce the number of images preceding the cookbook since it felt cluttered. I also think that the HTML table I was trying to use to specify the image placement was causing issues.

**Review by brian-rose — COMMENTED** [review]
This seems to fix #11!

I notice though that there are more missing images lower down in the notebook, e.g. https://cookbooks.projectpythia.org/mpl-colorbar-cookbook/_preview/11/notebooks/mpl-colorbar-cookbook.html#printing-in-black-and-white

**Comment by hCraker** [comment]
@brian-rose Thanks for pointing that out. I just fixed those images too. We should be good to go!

**Review by brian-rose — APPROVED** [review]
Looks great @hCraker!

**Pull request merged**
